### ISSUE TITLE
업무 분담

### ISSUE THREAD

**Issue by hesthers** [hesthers/cowork-practice#1]
어떤 분이 어떤 걸 담당하실지 댓글로 알려주세요..

각자 이름별로 되어있는 이슈 항목에 들어가셔서 체크리스트 눌러주세요

**Comment by alexholft** [comment]
음 팀장님 저는 fizzbuzz.py를 맡겠습니다

**Comment by hwanlloween** [comment]
그럼 저는 introduce하겠습니다

**Comment by tommytaeh** [comment]
그럼 저는 승환님이랑 같이 introduction하겠습니다

**Comment by alexholft** [comment]
Labels, Assignees, Projects, Milestone 설정해주세요 팀장님 (나중에)

**Comment by hesthers** [comment]
얼른 만들고 설정해드릴게요.. milestone은 작성해놓았으니 확인해주세요

**Comment by hwanlloween** [comment]
네네

**Comment by tommytaeh** [comment]
pull request했습니다. merge 부탁드립니다
