### ISSUE TITLE
재혁님 업무분담

### ISSUE THREAD

**Issue by hesthers** [hesthers/cowork-practice#3]
fizzbuzz.py 코딩 파일 작성해서 만들어주세요

todo list

- [x] fizzbuzz.py 코딩 초안 작성해주세요
- [x] approve 이후에 받아주세요
- [x] 본인 이름을 코딩에 작성해주세요 (커밋에 포함시켜주세요)

**Comment by alexholft** [comment]
fizzbuzz.py 코딩 초안 작성 완료했습니다

**Comment by hesthers** [comment]
pull request 해주세요~

**Comment by alexholft** [comment]
> pull request 해주세요~

pull request 완료했습니다

**Comment by alexholft** [comment]
이름 포함 했습니다

**Comment by hesthers** [comment]
수고하셨어요... issue 닫을 게요

**Comment by alexholft** [comment]
넵
