### ISSUE TITLE
태형님 업무분담

### ISSUE THREAD

**Issue by hesthers** [hesthers/cowork-practice#4]
태형님이 하셔야할 부분입니다.

todo list:

- [x] introduce.md 파일 승환님과 같이 작성해주시고 commit 잊지 말아주세요

- [x] approve 잊지 말고 받아주시구요

- [x] 팀이름과 본인 이름도 포함해서 함께 작성해주세요. (commit에 넣어주세요)

**Comment by tommytaeh** [comment]
넵 알겠습니다

**Comment by hesthers** [comment]
이슈 공간 클로즈 할게요.. 수고하셨어요
